In [11]:
from sklearn.feature_extraction.text import CountVectorizer
# More info about CountVectorizer:
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
import pandas as pd

In [6]:
documents = ['Hello, how are you!',
             'Win money, win from home.',
             'Call me now.',
             'Hello, Call hello you tomorrow?']

In [9]:
# Convert documents into a CountVector
count_vector = CountVectorizer(documents)

# Information about the count_vector object
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8',
                input=['Hello, how are you!', 'Win money, win from home.',
                       'Call me now.', 'Hello, Call hello you tomorrow?'],
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [14]:
# Fit method allows us to learn the vocabulary
count_vector = count_vector.fit(documents)

# Transform method convert documents into document-term matrix
# Finally, we convert the object into an array with .toarray()
doc_array = count_vector.transform(documents).toarray()
print(doc_array)

[[1 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 1 0 1 0 0 1 0 0 2 0]
 [0 1 0 0 0 0 1 0 1 0 0 0]
 [0 1 0 2 0 0 0 0 0 1 0 1]]


In [16]:
# Convert the array into a more legible format
df = pd.DataFrame(doc_array, columns=count_vector.get_feature_names())
print(df)

   are  call  from  hello  home  how  me  money  now  tomorrow  win  you
0    1     0     0      1     0    1   0      0    0         0    0    1
1    0     0     1      0     1    0   0      1    0         0    2    0
2    0     1     0      0     0    0   1      0    1         0    0    0
3    0     1     0      2     0    0   0      0    0         1    0    1
