In [14]:
import numpy as np

a0 = np.zeros((2,2)) # Create an array of all zeros

a1 = np.ones((1,2)) # Create an array of all ones

a_full = np.full((2,3), 7) # Create a constant array

a_identity = np.eye(3) # Create a 3x3 identity matrix

a_random = np.random.random((2,2)) #Create an array filled with random values

a_arange = np.arange(5,50,4) # arange([start,] stop[, step,], dtype=None)

# linspace(start, stop, num=50) num ->Number of samples to generate. Default: 50. Must be non-negative
a_linspace = np.linspace(0, 5, 6)

print(
"Array of all zeros -> a0: \n{}".format(a0),
"Array of all ones -> a1: \n{}".format(a1),
"Constant array -> a_full: \n{}".format(a_full),
"Identity matriz -> a_identity: \n{}".format(a_identity),
"Array filles with random values -> a_random: \n{}".format(a_random),
"Arange array -> a_arange: \n{}".format(a_arange),
"Linspace array -> a_linspace: \n{}".format(a_linspace),
sep="\n\n"
)

Array of all zeros -> a0: 
[[0. 0.]
 [0. 0.]]

Array of all ones -> a1: 
[[1. 1.]]

Constant array -> a_full: 
[[7 7 7]
 [7 7 7]]

Identity matriz -> a_identity: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array filles with random values -> a_random: 
[[0.81598014 0.67035318]
 [0.96015963 0.4166099 ]]

Arange array -> a_arange: 
[ 5  9 13 17 21 25 29 33 37 41 45 49]

Linspace array -> a_linspace: 
[0. 1. 2. 3. 4. 5.]
