## Create rank 1 & 2 arrays

In [2]:
import numpy as np

#### - First Way (Creating the array from a list)

In [3]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

array1 = np.array(list1)
array2 = np.array(list2)

print(array1, array2)

[1 2 3 4] [5 6 7 8]


In [10]:
big_list = [list1, list2] # [[1, 2, 3, 4], [5, 6, 7, 8]]

array = np.array(big_list)
print(array, "Array dimensions: {}".format(array.shape), sep="\n\n")

[[1 2 3 4]
 [5 6 7 8]]

Longitud del array (2, 4)


#### - Second Way (Creating the array directly)

In [11]:
a = np.array([1, 2, 3]) #1 dimensional array or rank 1 array
a[0] = 5

print("Type of the array: {}".format(type(a)), "Array dimensions: {}".format(a.shape), sep="\n")

Type of the array: <class 'numpy.ndarray'>
Array dimensions: (3,)


In [13]:
b = np.array([[1,2,3], [4,5,6]]) # Create a rank 2 array
print(b.shape)
print(b[0,0], b[0,1], b[1,0], sep=", ")

(2, 3)
1, 2, 4


### Slicing arrays

In [18]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

arr1 = arr[0][:2]
arr2 = arr[1][1::2]
print(arr1, arr2)

[1 2] [6 8]


##### Keep in mind that if you do change in slice, it affects the parent array

In [19]:
arr1[:] = 5
print(arr)

[[5 5 3 4]
 [5 6 7 8]]


In [20]:
arr_new = np.array(([0,1,2],[3,4,5]))

In [22]:
print(arr_new[:2, 1:3])

[[1 2]
 [4 5]]
