In [1]:
import numpy as np

#### Add

In [10]:
A = np.arange(20).reshape(4,5)
B = np.arange(20).reshape(4,5)
np.add(A,B)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

##### Sum the elements of the array

In [11]:
array_sum = np.array([[1,4,2],[5,8,3],[0,4,1]])
print(array_sum.sum())

28


#### Multiplication

In [2]:
mat1 = np.array([[1,2,3,4],[1,2,3,4]])
mat = mat1*mat1
print(mat)

[[ 1  4  9 16]
 [ 1  4  9 16]]


#### Dot product (Producto escalar) 

In [5]:
mat1 = np.array([[6,3,0], [2,5,1], [9,8,6]])
mat2 = np.array([[7,4], [6,7], [5,0]])
arr_dot = np.dot(mat1, mat2)

print(arr_dot)

[[ 60  45]
 [ 49  43]
 [141  92]]


#### Power

In [4]:
power = mat1**3
print(power)

[[ 1  8 27 64]
 [ 1  8 27 64]]


#### Square root

In [6]:
arr_sqrt = np.sqrt(arr_dot)
print(arr_sqrt)

[[ 7.74596669  6.70820393]
 [ 7.          6.55743852]
 [11.87434209  9.59166305]]


#### Exponential

In [7]:
arr_exp = np.exp(arr_dot)
print(arr_exp)

[[1.14200739e+26 3.49342711e+19]
 [1.90734657e+21 4.72783947e+18]
 [1.71997426e+61 9.01762841e+39]]


##### Standard deviation

In [13]:
tarray = np.array([[1,4,2],[5,8,3],[0,4,1]])
print(tarray.std())

2.3306863292670035
