In [2]:
import numpy as np

In [4]:
# copy() returns a separate copy
arr12 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr_copy = arr12.copy()
print(arr_copy)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# reshape(rows,columns) allows you to give the dimensions to the array
next_arr = np.arange(50).reshape(5,10)
print(next_arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [10]:
# arr.T rotate the dimensions of the array
arr_rotate = next_arr.copy()
print(arr_rotate.T)

[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


#### Method to select desired results from two arrays according to a boolean condition array:

In [18]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])

condition = np.array([True,True,False,False])

# we now want to choose from A if corresponding condition is True, and B if False
answer = [(A_val if cond else B_val) for A_val,B_val,cond in zip(A,B,condition)]

print(answer)

[1, 2, 300, 400]


##### <code>numpy.where()</code> is a easier method to do that:

In [22]:
answer2 = np.where(condition,A,B)
print(answer2)

[  1   2 300 400]


In [23]:
arr_test = np.array([.01, -8, -5, 4, 0, 3])
relu = np.where(arr_test > 0, arr_test, 0)
print(relu)

[0.01 0.   0.   4.   0.   3.  ]


In [24]:
tarray = np.array([[1,4,2],[5,8,3],[0,4,1]])
tarray.sort(0)
print(tarray)

[[0 4 1]
 [1 4 2]
 [5 8 3]]


In [25]:
country = np.array(['US','CN','IN','CN','SZ','US'])
np.unique(country)

array(['CN', 'IN', 'SZ', 'US'], dtype='<U2')